name: Build MuffinBite Cross-Platform

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build MuffinBite on Linux
        if: runner.os == 'Linux'
        run: pyinstaller --onefile --clean --name MuffinBite-linux muffinbite/management/cli.py

      - name: Build MuffinBite on Windows
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --clean --name MuffinBite.exe muffinbite/management/cli.py
        shell: powershell

      - name: Build MuffinBite on Mac
        if: runner.os == 'macOS'
        run: pyinstaller --onefile --clean --name MuffinBite-mac muffinbite/management/cli.py

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: MuffinBite-${{ runner.os }}
          path: dist/*